# Site settings
title: Export Layers
description: "GIMP plug-in that exports layers as separate images"
baseurl: "/gimp-plugin-export-layers"
url: https://khalim19.github.io
repository: khalim19/gimp-plugin-export-layers
github_username: khalim19
email: khalim19@gmail.com

plugin_version: 3.0-RC1
sections_url: /sections/
license_remote_url: blob/master/LICENSE
license_local_filename: LICENSE.txt
release_notes_filename: CHANGELOG.html

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata

# Build settings
markdown: kramdown
is_release_build: false
