# Site settings
title: Export Layers
site-title: Export Layers - GIMP Plug-in
description: "GIMP plug-in that exports layers as separate images"
baseurl: "/gimp-plugin-export-layers"
url: https://khalim19.github.io
github: [metadata]
repository: khalim19/gimp-plugin-export-layers
github_username: khalim19
email: khalim19@gmail.com

plugin-version: 3.0-RC1

gems:
  - jekyll-sitemap
  - jekyll-github-metadata

# Build settings
markdown: kramdown
